/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio1;

import javax.swing.JOptionPane;

/**
 *
 * @author baltamar
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad2 = new javax.swing.JTextField();
        txtCantidad3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPorcentaje1 = new javax.swing.JTextField();
        txtPorcentaje2 = new javax.swing.JTextField();
        txtPorcentaje3 = new javax.swing.JTextField();
        cmdCalcular = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        txtCantidad1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("INVERSIÓN DE EMPRESA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel2.setText("Cantidad 1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel3.setText("Cantidad 2");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel4.setText("Cantidad 3");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txtCantidad2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidad2KeyTyped(evt);
            }
        });
        jPanel1.add(txtCantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 280, -1));

        txtCantidad3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidad3KeyTyped(evt);
            }
        });
        jPanel1.add(txtCantidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 280, -1));

        jLabel5.setText("Porcentaje de inversión 1");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel6.setText("Porcentaje de inversión 2");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel7.setText("Porcentaje de inversión 3");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        txtPorcentaje1.setEditable(false);
        jPanel1.add(txtPorcentaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 110, -1));

        txtPorcentaje2.setEditable(false);
        jPanel1.add(txtPorcentaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 110, -1));

        txtPorcentaje3.setEditable(false);
        jPanel1.add(txtPorcentaje3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 110, -1));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        txtCantidad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidad1KeyTyped(evt);
            }
        });
        jPanel1.add(txtCantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 280, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
       String cantidad1,cantidad2,cantidad3;
       double cant1,cant2,cant3,op,porcentaje1,porcentaje2,porcentaje3;
       
         
        if(txtCantidad1.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Digite la cantidad numero uno"," error", JOptionPane.ERROR_MESSAGE);
            txtCantidad1.requestFocusInWindow();
        }
        else if(txtCantidad2.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Digite la cantidad numero dos"," error", JOptionPane.ERROR_MESSAGE);
            txtCantidad2.requestFocusInWindow();
        }
        else if(txtCantidad3.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Digite la cantidad numero tres"," error", JOptionPane.ERROR_MESSAGE);
            txtCantidad3.requestFocusInWindow();
        }
        
        else{
        
        cant1=Double.parseDouble(txtCantidad1.getText());
        cant2=Double.parseDouble(txtCantidad2.getText());
        cant3=Double.parseDouble(txtCantidad3.getText());
        op=cant1+cant2+cant3;
        porcentaje1=(cant1*100)/op;
        porcentaje2=(cant2*100)/op;
        porcentaje3=(cant3*100)/op;
       
        String porcen1=String.valueOf(porcentaje1);
        txtPorcentaje1.setText(porcen1);
        String porcen2=String.valueOf(porcentaje2);
        txtPorcentaje2.setText(porcen2);
        String porcen3=String.valueOf(porcentaje3);
        txtPorcentaje3.setText(porcen3);
       
        }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void txtCantidad1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad1KeyTyped
        
        char c=evt.getKeyChar(); 
             if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
               }     
    }//GEN-LAST:event_txtCantidad1KeyTyped

    private void txtCantidad2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad2KeyTyped
        
        char c=evt.getKeyChar(); 
             if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
               }
    }//GEN-LAST:event_txtCantidad2KeyTyped

    private void txtCantidad3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad3KeyTyped
       
        char c=evt.getKeyChar(); 
             if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
               }
    }//GEN-LAST:event_txtCantidad3KeyTyped

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        txtCantidad1.setText("");
        txtCantidad2.setText("");
        txtCantidad3.setText("");
        txtPorcentaje1.setText("");
        txtPorcentaje2.setText("");
        txtPorcentaje3.setText("");
        
        txtCantidad1.requestFocusInWindow();
        
    }//GEN-LAST:event_cmdBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCantidad1;
    private javax.swing.JTextField txtCantidad2;
    private javax.swing.JTextField txtCantidad3;
    private javax.swing.JTextField txtPorcentaje1;
    private javax.swing.JTextField txtPorcentaje2;
    private javax.swing.JTextField txtPorcentaje3;
    // End of variables declaration//GEN-END:variables
}
